version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"  
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "[composer dependencies] "
      
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"  
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "[npm dependencies] "
      
  - package-ecosystem: "npm"
    directory: "/tests/lib/screenshot-testing"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"  
      - "c: Tests & QA"
    groups:
      production-dependencies:
        dependency-type: "production"
    commit-message:
      prefix: "[UI test dependencies] "
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[GitHub Actions] "
    open-pull-requests-limit: 10
