version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
    commit-message:
      prefix: "[Composer] "
    reviewers:
      - "sgiehl"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: lockfile-only
    
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"  
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "[NPM] "
    reviewers:
      - "sgiehl"
    pull-request-branch-name:
      separator: "-"    
    versioning-strategy: lockfile-only
           
  - package-ecosystem: "npm"
    directory: "/tests/lib/screenshot-testing"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"  
      - "c: Tests & QA"
    groups:
      all-dependencies:
        patterns:
         - "*"
    commit-message:
      prefix: "[NPM UI Tests] "
    reviewers:
      - "sgiehl"
    pull-request-branch-name:
      separator: "-"    
    versioning-strategy: lockfile-only
           
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[GitHub Actions] "
    open-pull-requests-limit: 10
    reviewers:
      - "sgiehl"
    pull-request-branch-name:
      separator: "-"    
     
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      all-submodules:
        patterns:
         - "*"
    commit-message:
      prefix: "[Submodules] "
    reviewers:
      - "sgiehl"
    pull-request-branch-name:
      separator: "-" 
