
name: Build release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '4.x-dev'
        lfs: false
    - name: Check preconditions and create tag
      id: tag
      run: |
          version=$( cat core/Version.php | grep -oP "VERSION = '\K([^\']+)" )
          
          if [[ $( git tag --list $version ) -eq $version ]]
          then
            echo "A tag for $version already exists."
            exit 1
          fi
          
          echo "Creating a tag for $version"
          
          if [[ "$version" =~ "-" ]]
          then
            echo ::set-output name=prerelease::true
          else
            echo ::set-output name=prerelease::false
          fi;
                  
          echo ::set-output name=version::$version
      shell: bash 
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag.outputs.version }}
        prerelease: ${{ steps.tag.outputs.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}        
