
name: Build release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: false
        default: ''
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: "Check if user is in group"
      run: |
          MEMBER=$( curl -s \
                 --request GET \
                 --header 'authorization: Bearer ${{ secrets.GITTOKEN }}' \
                 --header 'content-type: application/json' \
                 --url https://api.github.com/orgs/matomo-org/teams/core-team/members \
                 | jq '.[] | select(.login == "${{ github.actor }}")' )
          
          if [[ -z "$MEMBER" ]]
          then
           echo "Action was not triggered by a member with release permission"
           exit 1;
          fi
      shell: bash
    - uses: actions/checkout@v2
      with:
        lfs: false
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.CERTIFICATE }}
        passphrase: ${{ secrets.CERTIFICATE_PASSWORD }}
    - name: Check preconditions and create tag
      id: tag
      run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]
          then
            version="${{ github.event.inputs.version }}"
            echo "Version to re-build: '$version'"
            
            git fetch --tags -q 2>/dev/null
            tag_exists=$( git tag --list "$version" )
          
            if [[ -z "$tag_exists" ]]
            then
              echo "A tag for $version does not exist."
              exit 1
            fi
            
            echo ::set-output name=update::true
          else
            version=$( cat core/Version.php | grep -oP "VERSION = '\K([^\']+)" )
            echo "Version to build: '$version'"
          
            git fetch --tags -q 2>/dev/null
            tag_exists=$( git tag --list "$version" )
          
            if [[ -n "$tag_exists" ]]
            then
              echo "A tag for $tag_exists already exists."
              exit 1
            fi
          
            echo "Creating a tag for $version"
          
            git tag $version
            git push origin tags/$version
            
            echo ::set-output name=update::false
          fi
          
          if [[ "$version" =~ "-" ]]
          then
            echo ::set-output name=prerelease::true
          else
            echo ::set-output name=prerelease::false
          fi
          
          git clone https://github.com/matomo-org/matomo-package.git matomo-package
          cd matomo-package
          ./scripts/build-package.sh $version
                    
          echo ::set-output name=version::$version
      shell: bash 
      continue-on-error: true
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "matomo-package/archives/matomo-${{ steps.tag.outputs.version }}.*"
        allowUpdates: ${{ steps.tag.outputs.update }}
        tag: ${{ steps.tag.outputs.version }}
        body: "artifacts"
        prerelease: ${{ steps.tag.outputs.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}        
