
name: Build release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: "Check if user is in group"
      run: |
          MEMBER=$( curl -s \
                 --request GET \
                 --header 'authorization: Bearer ${{ secrets.GITTOKEN }}' \
                 --header 'content-type: application/json' \
                 --url https://api.github.com/orgs/matomo-org/teams/core-team/members \
                 | jq '.[] | select(.login == "${{ github.actor }}")' )
          
          if [[ -z "$MEMBER" ]]
          then
           echo "Action was not triggered by a member with release permission"
           exit 1;
          fi
      shell: bash
    - uses: actions/checkout@v2
      with:
        lfs: false
    - name: Check preconditions and create tag
      id: tag
      run: |
          version=$( cat core/Version.php | grep -oP "VERSION = '\K([^\']+)" )
          
          echo "Version to build: '$version'"
          
          tag_exists=$( git tag --list "$version" )
          
          echo "-$tag_exists-"

          if [[ -n "$tag_exists" ]]
          then
            echo "A tag for $tag_exists already exists."
            exit 1
          fi
          
          echo "Creating a tag for $version"
          
          git tag $version
          git push origin tags/$version
          
          if [[ "$version" =~ "-" ]]
          then
            echo ::set-output name=prerelease::true
          else
            echo ::set-output name=prerelease::false
          fi
          
          git clone https://github.com/matomo-org/matomo-package.git matomo-package
          cd matomo-package
          ./scripts/build-package.sh $version matomo true
                    
          echo ::set-output name=version::$version
      shell: bash 
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "matomo-package/archives/matomo-${{ steps.tag.outputs.version }}.*"
        tag: ${{ steps.tag.outputs.version }}
        body: "artifacts"
        prerelease: ${{ steps.tag.outputs.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}        
