name: Update committed npm files

on:
  pull_request:

permissions:
  actions: read
  checks: none
  contents: write
  deployments: none
  issues: read
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v2
    - uses: actions/checkout@v4
      if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
      with:
        ref: ${{ github.head_ref }}
        submodule: false
        lfs: false
        persist-credentials: false
    - name: Prepare Git
      if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
      run: |
          cat <<- EOF > $HOME/.netrc
            machine github.com
            login $GITHUB_ACTOR
            password $GITHUB_TOKEN
            machine api.github.com
            login $GITHUB_ACTOR
            password $GITHUB_TOKEN
          EOF
          chmod 600 $HOME/.netrc

          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          git remote add upstream https://github.com/${GITHUB_REPOSITORY}.git
    - name: Install npm dependencies
      if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
      run: npm install --omit=dev
    - name: Push changes
      if: ${{ steps.dependabot-metadata.outputs.package-ecosystem == 'npm_and_yarn' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
      run: |
          git add ./node_modules
          git commit -m "Update npm dependencies"
          git push --set-upstream origin ${{ github.head_ref }}
      shell: bash
